
name: Dataset-workflow
env:
  KAGGLE_USERNAME: ${{secrets.KAGGLE_USERNAME}}
  KAGGLE_KEY: ${{secrets.KAGGLE_KEY}}

on:
  workflow_dispatch:

jobs:

  download_dataset:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: install package and download dataset
        run: |
          pip install kaggle
          pip install -r requirements.txt
          kaggle datasets download -d uwrfkaggler/ravdess-emotional-speech-audio
      - name: unzip dataset
        run: unzip ravdess-emotional-speech-audio.zip -d dataset
      - name: get feature csv
        run: python core/extract_features.py
#       - name: start train
#         run: python core/train.py
