name: Train-local-workflow
on:
  workflow_dispatch:
jobs:
  Train_CNN:
    runs-on: 
      - label-1
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: install package
      run: |
        pip install --upgrade pip
        pip install -r core/models/requirements.txt
    - name: train model and laod results
      run: python core/train.py --model CNN --epochs 50 --bs 100
      
  Train_DCNN:
    runs-on: 
      - label-2
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: install package
      run: |
        pip install --upgrade pip
        pip install -r core/models/requirements.txt
    - name: train model and laod results
      run: python core/train.py --model DCNN --epochs 50 --bs 100
    
  Train_LSTM:
    runs-on: 
      - label-1
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: install package
      run: |
        pip install --upgrade pip
        pip install -r core/models/requirements.txt
    - name: train model and laod results
      run: python core/train.py --model LSTM --epochs 10 --bs 100
        
  Train_RNN:
    runs-on: 
      - label-2
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: install package
      run: |
        pip install --upgrade pip
        pip install -r core/models/requirements.txt
    - name: train model and laod results
      run: python core/train.py --model RNN --epochs 20 --bs 100
        
